Possible to compile under open JDK 11.0
Make it possible to compile and run under openJDK 11.0:
Add (if needed) the javax classes, which had been removed from JDK 11.
See
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j
and other sources for more input.

Change compile.sh and createJAR.sh to allow to use both openJDK 11.0 or
Java 1.8

I don't have tested Java 1.7 (this is even older than 1.8), and a next step could be
to test openJDK 12.0